export const metadata = {
  title: "Terms & Conditions - countflows ",
  description:
    "Terms & Conditions for Text Tools. Learn about usage rules, disclaimers, intellectual property, and user responsibilities when using our online writing utilities.",
  alternates: {
    canonical: "https://countflows.com/terms",
  },
  openGraph: {
    title: "Terms & Conditions - countflows ",
    description:
      "countflows Terms & Conditions covering usage rules, disclaimers, intellectual property, and user responsibilities.",
    url: "https://countflows.com/terms",
    siteName: "countflows",
    type: "website",
  },
};

export default function TermsAndConditions() {
  return (
    <main className="max-w-4xl mx-auto px-6 mt-10 py-16 text-gray-800 dark:text-slate-200">
      <article aria-label="Terms and Conditions">
        <header>
          <h1 className="text-4xl font-bold mb-8 text-center">📜 Terms & Conditions</h1>
          <p className="mb-6 text-center text-lg">This page outlines the rules, responsibilities, and important information for using <strong>Text Tools</strong> and its features. Please review carefully.</p>
        </header>
        <section aria-labelledby="summary" className="mb-10">
          <h2 id="summary" className="text-2xl font-semibold mb-4">Summary</h2>
          <p className="mb-4">By using our website and tools (Word Counter, Sentence Counter, Reading Time Calculator, Character Counter), you agree to these Terms & Conditions. If you do not agree, please discontinue use of our website.</p>
          <ul className="list-disc pl-6 space-y-1 text-base">
            <li>Use our tools for lawful, personal, or professional purposes only.</li>
            <li>Respect our intellectual property and do not reproduce or modify our content without permission.</li>
            <li>Review our Privacy Policy for details on data collection and use.</li>
          </ul>
        </section>

        <section aria-labelledby="acceptance" className="mb-8">
          <h2 id="acceptance" className="text-2xl font-semibold mt-10 mb-4">1. Acceptance of Terms</h2>
          <p className="mb-6">By using our services, you acknowledge that you have read, understood, and agree to these Terms & Conditions. If you do not agree, please discontinue use of our website.</p>
        </section>

        <section aria-labelledby="use-of-tools" className="mb-8">
          <h2 id="use-of-tools" className="text-2xl font-semibold mt-10 mb-4">2. Use of Our Tools</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>Our tools are provided for educational, professional, and personal use only.</li>
            <li>You agree not to misuse our tools for unlawful, harmful, or fraudulent purposes.</li>
            <li>Results generated by our tools are based on researched formulas and linguistic analysis but may vary depending on text complexity and context.</li>
          </ul>
        </section>

        <section aria-labelledby="intellectual-property" className="mb-8">
          <h2 id="intellectual-property" className="text-2xl font-semibold mt-10 mb-4">3. Intellectual Property</h2>
          <p className="mb-6">All content, design, and functionality on Text Tools are the property of our platform. Unauthorized reproduction, distribution, or modification of our tools or content is strictly prohibited.</p>
        </section>

        <section aria-labelledby="disclaimer" className="mb-8">
          <h2 id="disclaimer" className="text-2xl font-semibold mt-10 mb-4">4. Disclaimer of Warranties</h2>
          <p className="mb-6">Our tools are provided “as is” without warranties of any kind. While we strive for accuracy, we do not guarantee that results will be error‑free or suitable for every purpose. Users are responsible for verifying outputs before relying on them.</p>
        </section>

        <section aria-labelledby="liability" className="mb-8">
          <h2 id="liability" className="text-2xl font-semibold mt-10 mb-4">5. Limitation of Liability</h2>
          <p className="mb-6">Text Tools shall not be held liable for any damages, losses, or issues arising from the use or inability to use our tools. Users assume full responsibility for their usage.</p>
        </section>

        <section aria-labelledby="third-party" className="mb-8">
          <h2 id="third-party" className="text-2xl font-semibold mt-10 mb-4">6. Third‑Party Services</h2>
          <p className="mb-6">We may use third‑party services such as Google AdSense for advertising. These services have their own policies, and we encourage users to review them separately.</p>
        </section>

        <section aria-labelledby="privacy" className="mb-8">
          <h2 id="privacy" className="text-2xl font-semibold mt-10 mb-4">7. Privacy Policy</h2>
          <p className="mb-6">Your use of Text Tools is also governed by our{' '}
            <a href="/privacy-policy" className="text-blue-500 hover:underline">Privacy Policy</a>, which explains how we collect, use, and protect your data.
          </p>
        </section>

        <section aria-labelledby="changes" className="mb-8">
          <h2 id="changes" className="text-2xl font-semibold mt-10 mb-4">8. Changes to Terms</h2>
          <p className="mb-6">We reserve the right to update or modify these Terms & Conditions at any time. Changes will be posted on this page, and continued use of our services constitutes acceptance of the updated terms.</p>
        </section>

        <section aria-labelledby="law" className="mb-8">
          <h2 id="law" className="text-2xl font-semibold mt-10 mb-4">9. Governing Law</h2>
          <p className="mb-6">These Terms & Conditions shall be governed by and construed in accordance with applicable laws. Any disputes will be subject to the jurisdiction of relevant courts.</p>
        </section>

        <section aria-labelledby="contact" className="mb-8">
          <h2 id="contact" className="text-2xl font-semibold mt-10 mb-4">10. Contact Us</h2>
          <p>If you have any questions about these Terms & Conditions, please contact us at:{' '}
            <a href="mailto:umairrao965@gmail.com" className="text-blue-500 hover:underline">umairrao965@gmail.com</a>.
          </p>
        </section>

        {/* Table of Key Terms */}
        <section aria-labelledby="key-terms" className="mb-12">
          <h2 id="key-terms" className="text-2xl font-semibold mt-10 mb-4">Key Terms Table</h2>
          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-sm mb-4">
              <thead>
                <tr className="bg-gray-100 dark:bg-slate-800">
                  <th className="border px-3 py-2">Term</th>
                  <th className="border px-3 py-2">Definition</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border px-3 py-2">User</td>
                  <td className="border px-3 py-2">Anyone accessing or using the Text Tools website or its features.</td>
                </tr>
                <tr>
                  <td className="border px-3 py-2">Services</td>
                  <td className="border px-3 py-2">All online tools and content provided by Text Tools.</td>
                </tr>
                <tr>
                  <td className="border px-3 py-2">Intellectual Property</td>
                  <td className="border px-3 py-2">All content, design, and code owned by Text Tools.</td>
                </tr>
                <tr>
                  <td className="border px-3 py-2">Third‑Party Services</td>
                  <td className="border px-3 py-2">External services (e.g., Google AdSense) used for advertising or analytics.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        {/* FAQ Section */}
        <section aria-labelledby="faq" className="mb-8">
          <h2 id="faq" className="text-2xl font-semibold mt-10 mb-4">Frequently Asked Questions</h2>
          <dl className="space-y-4">
            <div>
              <dt className="font-semibold">Can I use Text Tools for commercial projects?</dt>
              <dd className="ml-4">Yes, as long as you comply with these Terms & Conditions and do not redistribute or resell the tools themselves.</dd>
            </div>
            <div>
              <dt className="font-semibold">How often are these terms updated?</dt>
              <dd className="ml-4">We update our terms as needed. Please check this page regularly for changes.</dd>
            </div>
            <div>
              <dt className="font-semibold">Is my data safe?</dt>
              <dd className="ml-4">See our <a href="/privacy-policy" className="text-blue-500 hover:underline">Privacy Policy</a> for details on data protection.</dd>
            </div>
          </dl>
        </section>
      </article>
    </main>
  );
}
