export const metadata = {
  title: "Terms & Conditions - Text Tools",
  description:
    "Terms & Conditions for Text Tools. Learn about usage rules, disclaimers, intellectual property, and user responsibilities when using our online writing utilities.",
  alternates: {
    canonical: "https://yourdomain.com/terms-and-conditions",
  },
  openGraph: {
    title: "Terms & Conditions - Text Tools",
    description:
      "Text Tools Terms & Conditions covering usage rules, disclaimers, intellectual property, and user responsibilities.",
    url: "https://yourdomain.com/terms-and-conditions",
    siteName: "Text Tools",
    type: "website",
  },
};

export default function TermsAndConditions() {
  return (
    <section className="max-w-4xl mx-auto px-6 mt-10 py-16 text-gray-800 dark:text-slate-200">
      <h1 className="text-4xl font-bold mb-8 text-center">
        📜 Terms & Conditions
      </h1>

      <p className="mb-6">
        Welcome to <strong>Text Tools</strong>. By accessing or using our
        website and tools (Word Counter, Sentence Counter, Reading Time
        Calculator, Character Counter), you agree to comply with and be bound by
        the following Terms & Conditions. Please read them carefully.
      </p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">1. Acceptance of Terms</h2>
      <p className="mb-6">
        By using our services, you acknowledge that you have read, understood,
        and agree to these Terms & Conditions. If you do not agree, please
        discontinue use of our website.
      </p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">2. Use of Our Tools</h2>
      <ul className="list-disc pl-6 space-y-2">
        <li>
          Our tools are provided for educational, professional, and personal use
          only.
        </li>
        <li>
          You agree not to misuse our tools for unlawful, harmful, or fraudulent
          purposes.
        </li>
        <li>
          Results generated by our tools are based on researched formulas and
          linguistic analysis but may vary depending on text complexity and
          context.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-10 mb-4">3. Intellectual Property</h2>
      <p className="mb-6">
        All content, design, and functionality on Text Tools are the property of
        our platform. Unauthorized reproduction, distribution, or modification
        of our tools or content is strictly prohibited.
      </p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">4. Disclaimer of Warranties</h2>
      <p className="mb-6">
        Our tools are provided “as is” without warranties of any kind. While we
        strive for accuracy, we do not guarantee that results will be error‑free
        or suitable for every purpose. Users are responsible for verifying
        outputs before relying on them.
      </p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">5. Limitation of Liability</h2>
      <p className="mb-6">
        Text Tools shall not be held liable for any damages, losses, or issues
        arising from the use or inability to use our tools. Users assume full
        responsibility for their usage.
      </p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">6. Third‑Party Services</h2>
      <p className="mb-6">
        We may use third‑party services such as Google AdSense for advertising.
        These services have their own policies, and we encourage users to review
        them separately.
      </p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">7. Privacy Policy</h2>
      <p className="mb-6">
        Your use of Text Tools is also governed by our{" "}
        <a href="/privacy-policy" className="text-blue-500 hover:underline">
          Privacy Policy
        </a>
        , which explains how we collect, use, and protect your data.
      </p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">8. Changes to Terms</h2>
      <p className="mb-6">
        We reserve the right to update or modify these Terms & Conditions at any
        time. Changes will be posted on this page, and continued use of our
        services constitutes acceptance of the updated terms.
      </p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">9. Governing Law</h2>
      <p className="mb-6">
        These Terms & Conditions shall be governed by and construed in
        accordance with applicable laws. Any disputes will be subject to the
        jurisdiction of relevant courts.
      </p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">10. Contact Us</h2>
      <p>
        If you have any questions about these Terms & Conditions, please contact
        us at:{" "}
        <a
          href="mailto:your-email@example.com"
          className="text-blue-500 hover:underline"
        >
          your-email@example.com
        </a>
        .
      </p>
    </section>
  );
}
